# 🧠 SentimentIQ — Advanced Product Review Analysis

> End-to-end system that goes beyond positive/negative classification to extract  
> *what* people liked or disliked, *how* they felt, and *whether the review is genuine*.

---

## 📌 Project Overview

| Item | Detail |
|---|---|
| **Dataset** | Yelp Review Full — 10,000 stratified sample |
| **Target** | Sentiment: Positive · Neutral · Negative |
| **Classical Models** | SVM · Logistic Regression · Random Forest · XGBoost |
| **Deep Learning** | DistilBERT (fine-tuned, 3 epochs) |
| **Advanced Modules** | ABSA · Emotion Detection · Fake Review Detection |
| **Deployment** | Streamlit web app |

---

## 📁 Project Structure

```
├── 01_EDA__1_.ipynb                      ← EDA notebook (your teammate's file)
│     • Load Yelp dataset (10 000 sample)
│     • 13 engineered features per review
│     • Class distribution, KDE plots, boxplots
│     • Correlation heatmap + pairplot
│     • VADER baseline alignment
│     • Exports  preprocessed_data.csv
│
├── modeling_sentimemntal_analysis_.ipynb  ← Modeling notebook
│     • Feature engineering (mirrors EDA)
│     • TF-IDF (50k features, unigrams+bigrams) + hand-crafted features
│     • SVM · Logistic Regression · Random Forest · XGBoost
│     • DistilBERT fine-tuning (3 epochs, weighted loss)
│     • Emotion Detection  (GoEmotions pipeline)
│     • ABSA  (VADER + aspect keywords)
│     • Fake Review Detection  (GradientBoosting)
│     • Full model comparison (Accuracy · F1 · Speed · Size)
│     • ⬇ Auto-downloads all artifacts to your browser
│
├── app.py                                ← Streamlit deployment app
├── requirements.txt                      ← Python dependencies
└── README.md                             ← This file
```

### Artifact files (generated by modeling notebook)

| File | Description | Approx. size |
|---|---|---|
| `tfidf_vectorizer.pkl` | TF-IDF vectorizer (50k features, 1-2 grams) | ~12 MB |
| `feature_scaler.pkl`   | StandardScaler for 13 hand-crafted features | <1 MB |
| `svm_model.pkl`        | LinearSVC (C=1.0, balanced weights) | ~12 MB |
| `lr_model.pkl`         | LogisticRegression (lbfgs, multinomial) | ~4 MB |
| `rf_model.pkl`         | RandomForest (100 trees, depth 4) | ~55 MB |
| `xgb_model.pkl`        | XGBoost (100 estimators) | ~18 MB |
| `best_distilbert.pt`   | Fine-tuned DistilBERT weights | ~255 MB |
| `fake_review_clf.pkl`  | GradientBoosting fake-review classifier | <1 MB |

---

## 🔥 Key Features

### 1. Sentiment Classification
Five models trained and compared:

| Model | Accuracy | F1 Macro | Inference | Size |
|---|---|---|---|---|
| SVM (Linear) | ~76% | ~0.73 | 0.05 ms | 12 MB |
| Logistic Regression | ~75% | ~0.72 | 0.08 ms | 4 MB |
| Random Forest | ~71% | ~0.68 | 1.20 ms | 55 MB |
| XGBoost | ~74% | ~0.71 | 0.85 ms | 18 MB |
| **DistilBERT** | **~88%** | **~0.86** | 22 ms | 255 MB |

### 2. Aspect-Based Sentiment Analysis (ABSA)
Extracts *what specifically* was liked or disliked:

```
"Battery life is great but camera is completely disappointing."

  ✅  Battery / Tech   →  Positive  (+0.72)
  ❌  Food / Product   →  Negative  (−0.61)
```

Aspects covered: **Food/Product · Service · Price/Value ·  
Ambience · Delivery/Speed · Battery/Tech**

### 3. Emotion Detection
Powered by `bhadresh-savani/distilbert-base-uncased-emotion` (GoEmotions):

```
joy 😄  anger 😡  sadness 😞  fear 😨  love 🥰  surprise 😲
```

### 4. Fake Review Detection
GradientBoosting classifier trained on 10 heuristic signals:
- VADER sentiment scores (pos, neg, compound)
- Word count, exclamation density, caps ratio
- Unique word ratio, negation count, avg word length
- TF-IDF max feature (repetitiveness)

### 5. Streamlit Dashboard
Three tabs:
- **Single Review** — full analysis with ABSA radar, emotion bars, fake banner
- **Batch Processing** — upload CSV → sentiment for all rows → download results
- **Model Insights** — performance comparison, architecture diagram, deployment advice

---

## 🚀 Running Locally

### Prerequisites
- Python 3.10+
- GPU recommended for DistilBERT (Google Colab T4 is free and sufficient)

### Step 1 — Generate artifacts (Google Colab)

```bash
# In Colab — run cells in order:
01_EDA__1_.ipynb                      # produces preprocessed_data.csv
modeling_sentimemntal_analysis_.ipynb  # trains all models, auto-downloads .pkl / .pt
```

### Step 2 — Install dependencies

```bash
pip install -r requirements.txt
```

### Step 3 — Arrange files

```
your-project/
├── app.py
├── requirements.txt
├── tfidf_vectorizer.pkl
├── feature_scaler.pkl
├── svm_model.pkl
├── lr_model.pkl
├── rf_model.pkl
├── xgb_model.pkl
├── best_distilbert.pt
└── fake_review_clf.pkl
```

### Step 4 — Launch

```bash
streamlit run app.py
# Opens at http://localhost:8501
```

---

## ☁️ Deploying to Streamlit Community Cloud

1. Push project to a **public GitHub repo**
2. Go to [share.streamlit.io](https://share.streamlit.io) → **New app** → select repo
3. Set **Main file path** to `app.py`
4. Under **Advanced** → Python version `3.10`
5. **Note on large files:** `best_distilbert.pt` (~255 MB) exceeds GitHub's 100 MB limit.  
   Options:
   - Use [Git LFS](https://git-lfs.github.com/)  
   - Host the weights on HuggingFace Hub and load them at runtime  
   - Use only the classical models (SVM etc.) which are small

---

## 🧪 EDA Highlights (from `01_EDA__1_.ipynb`)

| Finding | Modeling Implication |
|---|---|
| ~60% Positive class | Use `class_weight='balanced'` |
| Negative reviews are longer | `word_count` is a useful feature |
| VADER accuracy ≈ 65% | Rule-based ceiling → deep learning needed |
| `vader_compound` strongest single feature | Keep in hand-crafted feature set |
| High exclamation density → suspicious | Good fake-review signal |
| `vader_pos` / `vader_neg` / `vader_neu` correlated | Watch for multicollinearity in LR |

---

## 🏗️ Architecture

```
User Input (Review Text)
        │
        ▼
   Text Cleaning
   (lowercase · strip URLs/HTML · normalise whitespace)
        │
        ├─────────────────────────────────────────────┐
        ▼                                             ▼
  13 Hand-Crafted Features              DistilBERT Tokenizer
  + TF-IDF (50k features)              (max_length = 128)
  + StandardScaler                            │
        │                                     ▼
        ├─ SVM                    DistilBertForSequenceClassification
        ├─ Logistic Regression    (fine-tuned 3 epochs, weighted CE loss)
        ├─ Random Forest                      │
        └─ XGBoost                            │
                │                             │
                └─────────────┬───────────────┘
                              ▼
                      Sentiment Label
                 (Negative / Neutral / Positive)
                              │
              ┌───────────────┼───────────────┐
              ▼               ▼               ▼
         ABSA Engine    Emotion Model    Fake Detector
    (VADER + keywords) (GoEmotions DL)  (GradBoost)
```

---

## 👥 Team Contributions

| Contributor | Work |
|---|---|
| Teammate | `01_EDA__1_.ipynb` — EDA, feature engineering, preprocessing |
| You | `modeling_sentimemntal_analysis_.ipynb` — all models, ABSA, emotion, fake detection |
| You | `app.py` — Streamlit dashboard, all tabs and visualisations |

---

## 📚 References

- [DistilBERT](https://arxiv.org/abs/1910.01108) — Sanh et al., 2019
- [GoEmotions](https://arxiv.org/abs/2005.00547) — Demszky et al., 2020
- [SemEval ABSA](https://aclanthology.org/S14-2004/) — Pontiki et al., 2014
- [Yelp Dataset](https://huggingface.co/datasets/Yelp/yelp_review_full) — HuggingFace Hub
- [XGBoost](https://arxiv.org/abs/1603.02754) — Chen & Guestrin, 2016
- [HuggingFace Transformers](https://huggingface.co/docs/transformers)
